baseURL = 'https://byfernando.com/panoramical_2025/'
languageCode = 'en-us'
title = 'PANORAMICAL'
theme = 'archie'
canonifyURLs = true

[params]
	customcss = ["css/custom.css"]

[menu]

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Exhibitions"
url = "/exhibitions/"
weight = 2

[[menu.main]]
name = "Press"
url = "/press/"
weight = 2

[[menu.main]]
name = "Media"
url = "/media/"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4